### ISSUE TITLE
Graphical structure editor

### ISSUE THREAD

**Issue by rwest** [GreenGroup/RMG-website#28]
Bill often mentions that it'd be nice to have a gui for editing structures.

One possibility is OLN™ JSDraw™. Perhaps not the easiest interface, but it is free for non-commercial use and, critically, it can do radicals. http://www.scilligence.com/web/jsdrawapis.aspx

**Comment by connie** [comment]
Closing this issue and assigning it to https://github.com/GreenGroup/RMG-website/issues/81
