### ISSUE TITLE
Unable to determine atom type for atom <Atom 'O>. in furan

### ISSUE THREAD

**Issue by rwest** [GreenGroup/RMG-website#34]
These URLs give a server error
http://dev.rmg.mit.edu/adjacencylist/furan
http://dev.rmg.mit.edu/adjacencylist/O1C=CC=C1

```
 143.         molecule.fromSMILES(str(identifier))

Exception Type: AtomTypeError at /adjacencylist/O1C=CC=C1
Exception Value: Unable to determine atom type for atom <Atom 'O>.
```

**Comment by connie** [comment]
This particular issue has been resolved, however note that the thermo for Furan through group additivity is way off due to not identifying it as aromatic.  Currently working on fixing that through https://github.com/GreenGroup/RMG-Py/pull/354
