### ISSUE TITLE
Property Display on solvation molecules

### ISSUE THREAD

**Issue by jabrownmit** [GreenGroup/RMG-website#74]
Wondering how to best display Solvent Descriptors molecule data. Example of water is given below: 

![screen shot 2014-07-01 at 1 05 58 pm](https://cloud.githubusercontent.com/assets/7807771/3446460/1e07a944-0142-11e4-86d3-7c56e0eb64db.png)

Wondering if something such as s_h should be S subscript h, or if Epsilon should be the Greek letter epsilon. 

Additionally, the solvent library molecules do not have a molecular structure outlined by solvent.py (as you can see the section under the header Structure is blank). Not sure if this is intended.

@bslakman

**Comment by connie** [comment]
Solvation data now displays headers indicating what the parameters mean.  So this issue is now closed.
